### ISSUE TITLE
Publish module to PSGallery

### ISSUE THREAD

**Issue by fullenw1** [sos-berlin/scheduler-cli-powershell#1]
Hello,

Please could you publish your module on PSGallery?

This would facilitate the deployment in an enterprise environment,
but would also increase the visibility of the product
when someone searches PowerShell modules with keywords like "schedule" or "job".

Typically, the first thing I did when a colleague told me about JobScheduler was to search if I can manage it with PowerShell.
Unfortunately, this command returned nothing:
```powershell
Find-Module -Name 'JobScheduler'
```

You worked hard to make a great module.
It's a pity that it is not published on PSGallery :)

**Comment by sosap** [comment]
Hi,

we published the JobScheduler module with PSGallery. The command should now return:

```powershell
Find-Module -Name 'JobScheduler'

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.2.0      JobScheduler                        PSGallery            Control jobs and job chains with JobScheduler Master and Agents, access the JOC Cockpit REST Web Service.
```

Best regards
Andreas
