### ISSUE TITLE
Start-JobSchedulerJob error with parameters

### ISSUE THREAD

**Issue by kayku** [sos-berlin/scheduler-cli-powershell#2]
https://www.powershellgallery.com/packages/JobScheduler/1.2.4/ContactOwners

Hi, I'm trying to run the "Start-JobSchedulerJob" cmdlet but if I add -Parameters
$params = @{'Parameter1'='123423'}   
                   *in the doc is bad formatted, the sample shows as --> $params=${"param"="val"}

Start-JobSchedulerJob -Job '/folder/Job' -Parameters @{'Parameter1'='123423'}

always return this error.
If try to run it without params returns ok.
On web I can add the param without errors
Thanks in advance!

This is the output :

IsMutuallyAuthenticated : False
Cookies                 : {}
Headers                 : {X-Frame-Options, X-Content-Type-Options, X-XSS-Protection, Content-Security-Policy...}
SupportsHeaders         : True
ContentLength           : 227
ContentEncoding         :
ContentType             : application/json
CharacterSet            :
Server                  : Jetty(9.4.18.v20190429)
LastModified            : 02/07/2021 13:35:34
StatusCode              : 420
StatusDescription       :
ProtocolVersion         : 1.1
ResponseUri             : http://xxxxxxxxxx.xxxx.net:4446/joc/api/jobs/start
Method                  : POST
IsFromCache             : False
En C:\Program Files\WindowsPowerShell\Modules\JobScheduler\1.2.4\functions\Start-JobSchedulerJob.ps1: 222 Carácter: 21
+ ...                 throw ( $response | Format-List -Force | Out-String )
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (
IsMutuallyA...: False
:String) [], RuntimeException
    + FullyQualifiedErrorId :
IsMutuallyAuthenticated : False
Cookies                 : {}
    Headers                 : {X-Frame-Options, X-Content-Type-Options, X-XSS-Protection, Content-Security-Policy...}

SupportsHeaders         : True
ContentLength           : 227
ContentEncoding         :
ContentType             : application/json
CharacterSet            :
Server                  : Jetty(9.4.18.v20190429)
LastModified            : 02/07/2021 13:35:34
StatusCode              : 420
StatusDescription       :
ProtocolVersion         : 1.1
ResponseUri             : http://xxxxxxxxxx.xxxx:4446/joc/api/jobs/start
Method                  : POST
IsFromCache             : False

**Comment by sosap** [comment]
Hi kayku,

thank for the bug report.

This issue is fixed with release 1.2.5 that is available from GitHub and PowerShellGallery

Best regards
Andreas
